### ISSUE TITLE
Add an option to use circles instead of hexagons

### ISSUE THREAD

**Issue by risingfish** [mwganson/honeycomb#1]
I've been having a lot of fun with the plugin, but I have run into a few cases where this would be even more handy if it generated circles. Would that be hard to add?

**Comment by mwganson** [comment]
Create a sketch on the xy plane.  Add only a circle to the sketch, make it radius of 1mm centered on the origin.  Select the sketch and run the macro.  Alternatively, edit the Honeycomb object's Profile property to point to the sketch
![Snip macro screenshot-ac26aa](https://user-images.githubusercontent.com/39143564/176233026-1a715135-b707-4cdc-8e70-760aeb136d71.png)
.

**Comment by risingfish** [comment]
Thank Mark, I missed that capability! This is a awesome macro.
